server:
  port: 20001
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20001/eureka
    register-with-eureka: true
    fetch-registry: false
