server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: city
          uri: lb://micro-city
          predicates:
            - Path=/city/**
        - id: hotel
          uri: lb://micro-hotel
          predicates:
            - Path=/hotel/**,/room/**
        - id: system
          uri: lb://micro-system
          predicates:
            - Path=/system/**,/citySystem/**,/hotelSystem/**
        - id: search
          uri: lb://micro-search
          predicates:
            - Path=/search/**
        - id: user
          uri: lb://micro-user
          predicates:
            - Path=/user/**
        - id: order
          uri: lb://micro-order
          predicates:
            - Path=/order/**,/pay/**